site_name: Curiosity into `Code`

nav:
  - Soft Skills:
      - Invisible Ownership Subtasks: soft-skills/Invisible Ownership Subtasks.md
      - Staying on Track When a Ticket Gets Complicated: soft-skills/Staying on Track When a Ticket Gets Complicated.md
  - Java:
    - How HashMap Handles Collisions: java/How HashMap Handles Collisions.md
    - Stay Friends with the Console: java/Stay Friends with the Console.md
    - Concurrency - Part 1: java/Concurrency - Part 1.md
    - Concurrency - Part 2: java/Concurrency - Part 2.md
    - Mock vs Spy in Mockito — Never Ask Again: java/Mock vs Spy in Mockito — Never Ask Again.md
    - Concurrency - Part 3: java/Concurrency - Part 3.md
    - Java Generics as a Compile-Time Gift With a Runtime Disguise: java/Java Generics as a Compile-Time Gift With a Runtime Disguise.md
    - Concurrency - Part 4: java/Concurrency - Part 4.md
    - Concurrency - Part 5: java/Concurrency - Part 5.md
    - Java’s Mission, No More Excuses: java/Java’s Mission - No More Excuses.md
    - How Threads Share Code in Java: java/How Threads Share Code in Java.md
    - Don’t Let Your Java Debugger Fool You: java/Don’t Let Your Java Debugger Fool You.md
  - Spring:
    - Method-Level Authorization in Spring Security: spring/Method-Level Authorization in Spring Security.md
    - How Singleton Components Work with Thread Pools: spring/How Singleton Components Work with Thread Pools.md
    - How to Scale Spring Boot for High Concurrency: spring/How to Scale Spring Boot for High Concurrency.md
    - If You Don’t Practice TDD, Do This Instead: spring/If You Don’t Practice TDD, Do This Instead.md
  - Design:
    - Don’t Mix Up Aggregates and Aggregators: design/Don’t Mix Up Aggregates and Aggregators.md
    - Don't Mix Up Polling and Pooling: design/Don't Mix Up Polling and Pooling.md
  - Data:
    - PostgreSQL Transactions - Part 2: data/PostgreSQL Transactions - Part 2.md
    - PostgreSQL Transactions - Part 1: data/PostgreSQL Transactions - Part 1.md
  - Security:
    - Seamless AWS Access - Setting Up Azure AD as a Federated Identity Provider: security/Seamless AWS Access - Setting Up Azure AD as a Federated Identity Provider.md
    - Defending Against XSS in React and JSP: security/Defending Against XSS in React and JSP.md
  - DevOps:
    - Using Nginx to Front Both Backend and Frontend: devops/Using Nginx to Front Both Backend and Frontend.md
    - Correlating Bamboo Concepts with AWS ECS: devops/Correlating Bamboo Concepts with AWS ECS.md
    - How Web Servers Handle Logging Efficiently: devops/How Web Servers Handle Logging Efficiently.md
    - Making the Invisible Visible: devops/Making the Invisible Visible.md

theme:
  name: material
  custom_dir: overrides
  logo: img/_logo.png
  favicon: img/favicon.ico

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - extra.css
