site_name: ~/moham/dev

plugins:
  - search
  - tags

theme:
  name: material
  logo: img/_logo.png
  favicon: img/favicon.ico

markdown_extensions:
  - pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
  - https://cdn.jsdelivr.net/npm/mustache@4.2.0/mustache.min.js

extra_css:
  - stylesheets/extra.css
