site_name: Curiosity into `Code`

nav:
  - Soft Skills:
      - Invisible Ownership Subtasks: soft-skills/Invisible Ownership Subtasks.md
  - Java:
    - How HashMap Handles Collisions: java/How HashMap Handles Collisions.md
    - Stay Friends with the Console: java/Stay Friends with the Console.md
  - Spring:
    - Method-Level Authorization in Spring Security: spring/Method-Level Authorization in Spring Security.md
    - How Singleton Components Work with Thread Pools: spring/How Singleton Components Work with Thread Pools.md
  - DevOps:
    - Correlating Bamboo Concepts with AWS ECS: devops/Correlating Bamboo Concepts with AWS ECS.md

theme:
  name: material
  custom_dir: overrides
  logo: img/_logo.png
  favicon: img/favicon.ico

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - extra.css
