site_name: ~/moham/dev

nav:
  - Moham: index.md
  - Java:
    - Primitive Data Types: java/Primitive Data Types.md
    - Method-Level Authorization in Spring Security: spring/Method-Level Authorization in Spring Security.md
  - Spring:
      - Primitive Data Types: java/Primitive Data Types.md
      - Method-Level Authorization in Spring Security: spring/Method-Level Authorization in Spring Security.md

theme:
  name: material
  logo: img/_logo.png
  favicon: img/favicon.ico

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - extra.css
