site_name: ~/moham/dev

nav:
  - Moham: index.md
  - Java:
    - Back: index.md
    - Primitive data types: java/Primitive data types.md
  - Spring:
      - Back: index.md
      - Method-level authorization in Spring Security: spring/Method-level authorization in Spring Security.md

theme:
  name: material
  logo: img/_logo.png
  favicon: img/favicon.ico

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - extra.css
